// Generated by https://quicktype.io
export interface Bus {
    id: number;
    numero: string;
    placa: string;
    activo: number;
    driver_id: number | null;
    statu_id: number | null;
    created_at: string;
    updated_at: string;
    status: string;
    id_user_actual: number;
}
